### ISSUE TITLE
Write pulsar-mqtt-source

### ISSUE THREAD

**Issue by haphut** [HSLdevcom/transitlog#4]
https://github.com/HSLdevcom/pulsar-mqtt-source

Collect any MQTT data into Pulsar. Run several instances for high availability.

Use a list of MQTT topic filters in the configuration to collect all MQTT data from VPCs into one topic. The ordering of the messages within the vehicle and in relation to other vehicles matters when the vehicle clocks cannot be trusted.

Implement using Pulsar IO.

Do not run within the Pulsar cluster. Use either Pulsar Java Admin API or Pulsar Admin CLI to run locally on Docker host / Docker Swarm.

**Comment by paasovaara** [comment]
https://github.com/HSLdevcom/mqtt-pulsar-gateway implements this.
