### ISSUE TITLE
Transform HFP into GraphQL mutations

### ISSUE THREAD

**Issue by haphut** [HSLdevcom/transitlog#6]
Transform HFP messages into GraphQL mutations. Implement using Pulsar Functions.

Possibly bundle Pulsar messages to send only e.g. 10 mutations/s into Hasura. Bundle e.g. at least every 100 ms or at most every 1000 messages, whichever condition is fulfilled first.

**Comment by paasovaara** [comment]
implemented using sql inserts to postgresql. this way insert speed is good enough, roughly 100ms for 1000 events (rows) in our sandbox server. 

Using hasura was too slow.
